Implementando edicao
IsaqueAmorim/CodersGrowth pull request #5
Opened 2023-04-18 17:28 UTC by IsaqueAmorim

2023-04-18 18:19 UTC, marcofeitosa requested changes

2023-04-18 18:19 UTC, marcofeitosa commented on CRUD/FML_Cadastro.cs
> +            Jogadores = lista;
Pq executa essa instrução duas vezes?

2023-04-18 18:19 UTC, marcofeitosa commented on CRUD/FML_Cadastro.cs
> +                Nome = TXB_Nome.Text,
Essa obtenção de dados pode ser feita em um método separado, e então vc chama ele nos métodos de criação e edição. Com isso evita repetição de código e atende ao Princípio da Responsabilidade Única

2023-04-18 18:19 UTC, marcofeitosa commented on CRUD/FML_Cadastro.cs
> +            if (Jogador == null)
Daria pra inverter a ordem de hierarquia entre o if/else e o try/catch

2023-04-18 18:19 UTC, marcofeitosa commented on CRUD/FML_Listagem.cs
> +        private void PopulandoLista()
Nesse momento não precisa mais desse método, já que pode o método de criação tá implementado

2023-04-18 22:50 UTC, IsaqueAmorim commented
Pronto, tudo atualizado! Tinha só um pouquinho de repetição de código kkkkkkkkkkkk

2023-04-19 11:27 UTC, marcofeitosa approved these changes

2023-04-19 11:27 UTC, merged